#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'
require_relative 'support/helpers'

PATH = FileUtils.pwd
HOME = get_home_directory
TRASH = "#{HOME}/.Trash/dotfiles-#{Time.now.to_i}"
FileUtils.mkdir(TRASH)

DOTFILES = %w[
  ackrc
  aliases
  gemrc
  gitconfig
  gvimrc
  rdebugrc
  rvmrc
  vimrc
  zlogin
  zshrc
]

install_vim
symlink_dotfiles

run_script(:clone_wegowise, "Cloning wegowise repos")
run_script(:keyboard_shortcuts, "Setting up keyboard shortcuts")
run_script(:default_shell, "Defaulting to zsh")

notify_todos(
  "Remap Caps Lock -> Control (System Preferences > Keyboard > Modifier Keys)",
)
