#!/usr/bin/env ruby

# thanks, tammer: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [ 
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/vim-scripts/bufkill.vim.git",
  "git://github.com/scrooloose/nerdtree"
]

peepopen = "git://github.com/topfunky/PeepOpen-EditorSupport.git"

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["gist",          "15897", "plugin"],
  ["jquery",        "15752", "syntax"],
  ["autoclose",     "9223",  "plugin"]
]

rcfiles = %w{vimrc gvimrc}

require 'fileutils'
require 'open-uri'

unless path = FileUtils.pwd.match(/^\/Users\/[^\/]*\/\.vim$/)
  raise ArgumentError, "you must clone the git repo directly into /Users/<username>/.vim/"
end

puts "Symlink dotfiles (delete old ones)"
rcfiles.each do |rcfile|
  FileUtils.rm_f("../.#{rcfile}")
  FileUtils.ln_s("#{path}/#{rcfile}", "../.#{rcfile}")
end

puts "Trashing all bundles (lookout!)"
FileUtils.rm_rf 'bundle'
FileUtils.mkdir('bundle')

puts "Making symbolic links for vimballs"
Dir.entries('vimballs').each do |item|
  next if ['.','..'].include?(item) || !File.directory?("vimballs/#{item}")
  FileUtils.ln_s "vimballs/#{item}", "bundle/#{item}"
end

FileUtils.cd('bundle')

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "\nUnpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end


puts "\nUnpacking #{peepopen} into vim-peepopen"
tmpfolder = "/tmp/vim-peepopen-#{Time.now.to_i}"
`git clone #{peepopen} #{tmpfolder}`
FileUtils.mv("#{tmpfolder}/vim-peepopen/",'vim-peepopen/')
FileUtils.rm('vim-peepopen/README.md')

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
