#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'
require_relative 'support/helpers'

PATH = FileUtils.pwd
HOME = get_home_directory
TRASH = "#{HOME}/.Trash/dotfiles-#{Time.now.to_i}"
FileUtils.mkdir(TRASH)

BREW_FORMULAS = %w[
  caskroom/cask/brew-cask
  chruby
  git
  memcached
  macvim
  mysql
  node
  postgres
  redis
  ruby-install
]

BREW_CASK_FORMULAS = %w[
  rowanj-gitx
]

DOTFILES = %w[
  ackrc
  aliases
  gemrc
  gitconfig
  gvimrc
  rdebugrc
  rvmrc
  vimrc
  zlogin
  zshrc
]

install_homebrew_formulas
install_vim
symlink_dotfiles
copy_bin_scripts

run_script(:symlink_mvim_to_applications, "Symlink MacVim to /Applications/")
run_script(:clone_wegowise, "Cloning wegowise repos")
run_script(:keyboard_shortcuts, "Setting up keyboard shortcuts")
run_script(:turn_off_autocorrect, "Turn off autocorrect")
run_script(:default_shell, "Defaulting to zsh")
run_script(:set_startup_services, "Configuring startup services")

notify_todos(
  "Remap Caps Lock -> Control (System Preferences > Keyboard > Modifier Keys)",
  "run `vim_setup` from the command line",
  "Add Terminal themes (see README in folder)",
  "Add `mvim` to /usr/local/bin",
  "Enable Terminal usage for GitX",
  "Install Ruby for Wego via: `cd wegowise` and `install_ruby`",
  "Download PSequel.app and Sequel Pro",
  "Install XCode and Command Line Tools (probably already had to do this)"
)
