#!/usr/bin/env ruby

# thanks, tammer: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [ 
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/mileszs/ack.vim.git"
]

peepopen = "git://github.com/topfunky/PeepOpen-EditorSupport.git"

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["gist",          "15897", "plugin"],
  ["jquery",        "15752", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }
FileUtils.rm_rf '/tmp/vim-peepopen'

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end


puts "  Unpacking #{peepopen} into vim-peepopen"
`git clone #{peepopen} /tmp/vim-peepopen`
FileUtils.mv('/tmp/vim-peepopen/vim-peepopen/','vim-peepopen/')
FileUtils.rm('vim-peepopen/README.md')

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
