version: '3.3'
services:
  mysql_5_7:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '5724:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql